### ISSUE TITLE
How long does it take to start the creation of a node?

### ISSUE THREAD

**Issue by jasdefer** [Azure/Batch#145]
I have a question:
I want to create a new pool or resize a pool from 0 to 1 or multiple dedicates nodes. It takes between 3 and 8 minutes before a node starts to get created. The creation itself is fast, because I use `ubuntu-server-container` with a prefetched docker image. 
Are those 3 to 8 minutes normal, or is it possible to reduce this duration? I am happy to be pointed to any documentation about this topic as well. Thank you very much!

**Comment by MatthewSteeples** [comment]
I don't think you'll get an official response on this because a lot of it depends on how busy Azure is in general at the time of your request. We tend to see a similar times to what you're looking at when adding a couple of VMs. Anecdotally, I've seen that trying to add a large number of VMs at once doesn't increase the time for the first few to be ready, but they won't all be finished in your 10 minute window.

See https://social.msdn.microsoft.com/Forums/azure/en-US/ccdfb50e-0585-4670-94a6-13b0a4f577a4/how-long-time-does-it-take-to-resize-the-pool?forum=azurebatch

**Comment by staer** [comment]
As @MatthewSteeples points out, start up time is going to vary quite a bit due to a number of factors such as the number of VMs requested, the VM SKU used, the image requested, the region, the current load on Batch, and a variety of other things. To my knowledge, there is no official SLA on VM start times for either Batch or Azure as a whole.

**Comment by jasdefer** [comment]
Thank you very much. Too bad there is not even an upper limit, so we need to design our application for edge cases where it takes multiple hours or even longer.
