### ISSUE TITLE
Clarify meaning of "Node allocation time"

### ISSUE THREAD

**Issue by letmaik** [Azure/Batch#25]
I'm using low-priority nodes and try to understand what "node allocation time" means. This is what it shows in the Azure Portal:

![image](https://user-images.githubusercontent.com/530988/46205102-69b60200-c317-11e8-9be0-78720ab5cc15.png)

My confusion here is with preemption of nodes. If a node gets preempted such that a new node has to join the pool, would that mean that the allocation time is reset? Or does it stay at the initial value and the logical "node" does not in fact leave/join the pool but is just receiving a VM under the covers?

What confuses me in the screenshot above is that the last boot time seems to be way after allocation, so maybe when the node got preempted? It's quite hard to really understand what's happening without a more detailed historic log.

**Comment by matthchr** [comment]
We can definitely improve the documentation here.

To answer your specific question though, allocation time is indeed the time that node logical node is allocated for the first time. This is unaffected by preemption (as the logical node hasn't changed, it has the same name, etc).

Last boot time is the last time the Batch agent running on the node booted. That means it will get updated when any of the following happen:
1. The node boots for the first time
2. The node reboots (due to user request or due to an underlying Azure infrastructure issue)
3. The node is reimaged
4. The node is preempted and then is recovered by batch

@alfpark you can probably assign this to me and I can improve the documentation on these properties for our next API version.

**Comment by matthchr** [comment]
I've made some improvements to the docs which should be making their way public in the next week or so. @alfpark I believe we can close this

**Comment by letmaik** [comment]
@matthchr Can you link to the commit(s) that changed it?

**Comment by matthchr** [comment]
It's not actually merged yet, it's included in [this PR](https://github.com/Azure/azure-rest-api-specs/pull/4795)
