### ISSUE TITLE
Allow for ResourceFile mapping on target node to shorten file paths when using ResourceFile.FromStorageContainerUrl

### ISSUE THREAD

**Issue by Mohammed-El-Nabulsi** [Azure/Batch#60]
Hey,

we are currently updating to the newest version of the Azure Batch SDK and noticed an issue that will prevent us from using 

`ResourceFile.FromStorageContainerUrl()`

properly. The issue is that (due to historical reasons) the canonical file paths of our Azure blob resources are deeply nested and thus very long. We cannot change that at the moment.

Thus, when issuing 

```
List<ResourceFile> jobResourceFiles = new List<ResourceFile>()
{
	ResourceFile.FromStorageContainerUrl(uploadsContainerUri, blobPrefix:projectDirectory.CanonicalPath)
};
```

on our end it results in file paths longer than the supported max length on Windows nodes because the SDK retains the entire path after download. Example (details blurred due to NDAs):

`root/workitems/190504190821_5ccdc6f58be91200907f3d80_suffix/job-1/jobpreparation/wd/long-path-segment/long-path-segment/file-name`

What would help us out here is to stop retaining the entire file path per default and allow for a mapping so that we can skip the entire file path retained from Azure blob storage:

`root/workitems/190504190821_5ccdc6f58be91200907f3d80_suffix/job-1/jobpreparation/wd/file-name`

Until then we see ourselves stuck at version 9 of the SDK where we can still initialize ResourceFiles via the constructor and custom SAS Keys.

If you have any workaround for this that we currently do not see please don't hesitate to point that out.

Thanks for all the help!

Kind regards

Mo

**Comment by bgklein** [comment]
Addressing the problem of 'Until then we see ourselves stuck at version 9 of the SDK', if you have working solution targeting an older version of the SDK you should be able to upgrade and keep existing functionality by using FromHttpUrl instead of blob source. This functionality should be sufficient for existing workloads to migrate to newer SDKs.

I will leave the feature request to be addressed by others.

**Comment by Mohammed-El-Nabulsi** [comment]
Thanks for the reply. So what you are suggesting is to add the SAS URI to `FromHttpUrl`, am I correct? Good point!

**Comment by bgklein** [comment]
@Mohammed-El-Nabulsi Yep! To my knowledge the underlying behavior/implementation should be the same, just with expanded coverage for any generic http url as well(not restricted to azure blobs).

**Comment by alfpark** [comment]
Please see #11 regarding enabling long file names.

It is unlikely that we would support a collating/coalescing/strip function on container downloads due to potential object name conflicts. If you need this functionality, considering implementing your own data transfer solution as part of job prep or the first execution step in a task. [blobxfer](https://github.com/Azure/blobxfer) supports a "strip components" option.
