### ISSUE TITLE
Certificates from KeyVault instead of uploading them to Batch

### ISSUE THREAD

**Issue by protointent** [Azure/Batch#93]
#### Feature Request Description
Batch should support getting the Certificates from a KeyVault instead of uploading them to Batch
This will reduce the duplication in Certificate management and secret rotation

#### Describe Preferred Solution
Batch should provide the surface to register certs as (keyvault, certname) with the batch account and store that associated with a moniker
Certificate references should be via moniker not via thumbprint as the thumbprint changes during secret rotation

The access to keyvault could be via the managed identity of the batch account, similar to the ADFv2 setup.

#### Describe Alternatives Considered
Upload to a KeyVault associated with the batch, but that would not help with rotation and propagation. Would be just another hop in chain. But would be similar to the autostorage.

#### Additional Context
Certificates need rotation, and that is usually done directly via KeyVault
Currently certificates are uploaded to Batch via own API and then consumed via references in pools
When a certificate is rotates, one need to go add the new cert (new thumbprint) and also remove old certificates.

**Comment by protointent** [comment]
Could consider using the Keyvault for credentials and secrets like the ones in MountConfiguration

**Comment by alfpark** [comment]
Although no timelines can be shared at this point, we are actively working in conjunction with the Azure Identity team to deliver a solution for this using Managed Identity.

**Comment by alfpark** [comment]
You can now create pools with Managed Identities: https://docs.microsoft.com/azure/batch/managed-identity-pools

We have a preview feature that allows you to add certain VM extensions to pools, including KeyVault VM extension: https://docs.microsoft.com/azure/batch/create-pool-extensions

Using both together should allow your use case. Note that the VM extension on pools needs to be enabled on your account since it's not yet GA. Please raise a support ticket to enable the feature.
